version: '3.8'

services:
  backend:
    build:
      context: ./currency
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./currency_frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge